## 00. Pytorch Fundamentals

## Introduction to Tensors
### Creating ternsor

Pytorch tensors are created using torch.tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Mpsが利用されているかを確認
# 期待値　tensor([1.], device='mps:0')
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


In [2]:
# scalar 1 つの数字
scalar = torch.tensor(7)
print(scalar.ndim)
# 単一の値を含むテンソルからPythonの数値を取得するために使用します
print(scalar.item())

0
7


In [3]:
# Vector 方向を持つ数値 (例: 風速と方向) ですが、他の多くの数値を持つこともできます
vector = torch.tensor([7, 7])
vector.ndim, vector.shape

(1, torch.Size([2]))

In [4]:
# Matrix 数値の 2 次元配列
# 大文字は一般的です
MATRIX = torch.tensor([[1, 3],
                       [2, 4]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])

tensor([[1, 3],
        [2, 4]])
2
torch.Size([2, 2])
tensor([1, 3])


In [5]:
# Tensor 数値の n 次元配列
# 大文字は一般的です
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [5, 6, 7]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][1][1])

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])
3
torch.Size([1, 3, 3])
tensor(4)


### Random tensors
Why random tensors?

PyTorch を使用して機械学習モデルを構築する場合、テンソルを手作業で作成することはめったにありません (私たちが行ってきたように)。

代わりに、機械学習モデルは多くの場合、数値の大きなランダムなテンソルから開始し、データを介してこれらの乱数を調整して、データをより適切に表現します。

データ サイエンティストは、機械学習モデルの開始方法 (初期化)、データの表示方法、乱数の更新 (最適化) を定義できます。

Torch random tensors - https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [6]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim


(tensor([[0.6824, 0.4339, 0.7100, 0.4324],
         [0.1593, 0.0316, 0.4038, 0.4528],
         [0.5886, 0.0108, 0.5766, 0.2656]]),
 2)

In [7]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # R, G ,B
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [8]:
# Create a tensor of all zeros
zeros = torch.zeros((3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# create a tensor of all ones
ones = torch.ones((3, 4))
ones.dtype, ones

(torch.float32,
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

### Creating a range of tensors and tensors-like

In [10]:
# Use torch.range(0, 10)
torch.range(0, 10)
torch.arange(0, 10)
one_to_ten = torch.arange(start=1, end=10, step=2)
one_to_ten

/var/folders/j9/tvcjtl9x42jdg7mfpg1_w0j80000gn/T/ipykernel_46746/3498912548.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([1, 3, 5, 7, 9])

In [11]:
# Create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes
[PyTorch には、さまざまなテンソルデータ型があります。](https://docs.pytorch.org/docs/stable/tensors.html#data-types)

CPUに固有のものもあれば、GPUに適したものもあります。

どちらがいいかを知るには、時間がかかることがあります。

通常、どこかで torch.cuda を見かけると、テンソルが GPU に使用されています (Nvidia GPU は CUDA と呼ばれるコンピューティングツールキットを使用しているため)。

最も一般的な型 (そして一般的にはデフォルト) は torch.float32 または torch.float です。

これは「32ビット浮動小数点」と呼ばれます。

ただし、16 ビット浮動小数点 (torch.float16 または torch.half) と 64 ビット浮動小数点 (torch.float64 または torch.double) もあります。

さらに混乱させるのは、8ビット、16ビット、32ビット、64ビットの整数です。

さらに、もっと!

手記：整数は 7 のような平らな丸い数ですが、浮動小数点数の小数は 7.0 です。

これらすべての理由は、コンピューティングの精度に関係しています。

精度は、数値を説明するために使用される詳細の量です。

精度の値 (8、16、32) が高いほど、数値の表現に使用されるデータの詳細度が高くなります。

ディープラーニングや数値計算では、非常に多くの演算を行うため、計算する詳細度が高ければ高いほど、より多くの計算を使用する必要があるため、これは重要です。

そのため、精度の低いデータ型は一般的に計算が高速になりますが、精度などの評価メトリックのパフォーマンスが一部犠牲になります (計算は高速ですが、精度は低くなります)。


In [12]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 4.0, 5.0],
                                dtype=torch.float32,  # defaults to None, which is torch.float32 or whatever datatype is passed
                                device="mps", # defaults to None, which uses the default tensor type
                                requires_grad=False) # if True, operations performed on the tensor are recorded 
float_32_tensor

tensor([3., 4., 5.], device='mps:0')

In [13]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], device='mps:0', dtype=torch.float16)

In [14]:
float_32_tensor * float_16_tensor

tensor([ 9., 16., 25.], device='mps:0')

### Getting information from tensors
- 形状 - テンソルの形状は何ですか?(一部の操作には特定の形状ルールが必要です)
- dtype - テンソル内の要素はどのデータ型に格納されていますか?
- デバイス - テンソルはどのデバイスに格納されていますか?(通常はGPUまたはCPU)

In [15]:
# Create a tensor
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.1515, 0.4290, 0.8059, 0.6290],
        [0.3464, 0.7190, 0.4837, 0.6463],
        [0.9553, 0.6466, 0.0363, 0.1495]])
Datatype of tensor: torch.float32
torch.Size([3, 4])
cpu


## テンソルの操作(テンソル演算)
* 足し算
* 減算
* 乗算(要素ごと)
* 除法
* 行列の乗算

In [16]:
tensor = torch.tensor([1, 3, 5])
print(tensor + 10)
print(tensor - 10)
print(tensor * 10)
print(tensor / 10)
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([11, 13, 15])
tensor([-9, -7, -5])
tensor([10, 30, 50])
tensor([0.1000, 0.3000, 0.5000])
tensor([10, 30, 50])
tensor([11, 13, 15])


### 行列の乗算(Matrix multiplication)

In [17]:
# 1*1 + 2*2 + 3*3
# Matrix multiplication
# 2つの1Dベクトル(shape = (3,))がtorch.matmulに渡されると、
# PyTorchは自動的にそれらをベクトルのドット積として解釈し、
# これはNumPyのnp.dotの動作と一致します。
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([1, 2, 3])
torch.matmul(tensor_a, tensor_b)
# torch.mm(tensor_a, tensor_b)
# tensor_a @ tensor_b

tensor(14)

### 深層学習で最も一般的なエラーの 1 つ (形状エラー)
ディープラーニングの多くは乗算と行列に対する演算の実行であり、行列には組み合わせることができる形状とサイズについて厳密なルールがあるため、ディープラーニングで遭遇する最も一般的なエラーの 1 つは形状の不一致です。

1. 内側の寸法は、次のものと一致する必要があります。
* (3, 2) @ (3, 2) が機能しない
* (2, 3) @ (3, 2) が機能します
* (3, 2) @ (2, 3) が機能します
2. 結果の行列は、外形寸法の形状になります。
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

> **Note** http://matrixmultiplication.xyz/


In [18]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)


行列の乗算をtensor_Aとtensor_Bの間で機能させるには、それらの内部寸法を一致させます。

これを行う方法の1つは、転置(特定のテンソルの次元を切り替える)を使用することです。

PyTorch では、次のいずれかを使用して転置を実行できます。

* torch.transpose(input, dim0, dim1) - ここで、input は転置する目的のテンソルで、dim0 と dim1 はスワップする次元です。
* tensor_B.T - ここで、tensor は転置する目的のテンソルです。

In [19]:
print(torch.matmul(tensor_A, tensor_B.T))

# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### 最小、最大、平均、合計などの検索(集計)

In [20]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(x, x.dtype)
print(torch.min(x))
print(x.min())
print(torch.max(x))
print(x.max())
# torch.mean() などの一部のメソッドでは、テンソルが torch.float32 (最も一般的) 
# または別の特定のデータ型にある必要があり、そうしないと操作が失敗します。
print(torch.mean(x.type(torch.float32)))
print(torch.sum(x))
print(x.sum())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) torch.int64
tensor(0)
tensor(0)
tensor(90)
tensor(90)
tensor(45.)
tensor(450)
tensor(450)


In [21]:
# ポジショナル最小/最大
print(x.argmax())
print(x.argmin())

tensor(9)
tensor(0)


### Reshaping, stacking, squeezing and unsqueezing

|Method|One-line description|
|-|-|
|torch.reshape(input, shape)	|Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().|
|Tensor.view(shape)	|Returns a view of the original tensor in a different shape but shares the same data as the original tensor.|
|torch.stack(tensors, dim=0)	|Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.|
|torch.squeeze(input)	|Squeezes input to remove all the dimenions with value 1.|
|torch.unsqueeze(input, dim)	|Returns input with a dimension value of 1 added at dim.|
|torch.permute(input, dims)	|Returns a view of the original input with its dimensions permuted (rearranged) to dims.|

In [22]:
# create a tensor
x = torch.arange(1., 10.)
print(x, x.shape)

# add an extra dimension
# x_reshaped = x.reshape(1, 9)
x_reshaped = x.reshape(3, 3)
print(x_reshaped, x_reshaped.shape)

# change the view
z = x.view(3, 3)
print(z, z.shape)

# change z changes x ,viewが変更されたら、xも変更される。メモリアドレスは同じだから
z[:, 0] = 5
print(z, x)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) torch.Size([3, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) torch.Size([3, 3])
tensor([[5., 2., 3.],
        [5., 5., 6.],
        [5., 8., 9.]]) tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])


In [23]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x], dim = 1)
print(x)
print(x_stacked, x_stacked.shape)

tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
tensor([[5., 5.],
        [2., 2.],
        [3., 3.],
        [5., 5.],
        [5., 5.],
        [6., 6.],
        [5., 5.],
        [8., 8.],
        [9., 9.]]) torch.Size([9, 2])


In [24]:
# squeeze tensors
x = torch.zeros(2, 1, 2, 1, 2)
x_squeeze = torch.squeeze(x)
print(x_squeeze, x_squeeze.size())
# x_squeeze = torch.squeeze(x, 0)
# print(x_squeeze, x_squeeze.size())
# x_squeeze = torch.squeeze(x, 1)
# print(x_squeeze, x_squeeze.size())

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]) torch.Size([2, 2, 2])


In [25]:
# torch.unsqueeze()
print(f"Previous target: {x_squeeze}")
print(f"previous shape: {x_squeeze.shape}")

x_unsqueezed = x_squeeze.unsqueeze(dim=1)
print(x_unsqueezed, x_unsqueezed.shape)

Previous target: tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
previous shape: torch.Size([2, 2, 2])
tensor([[[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]]]) torch.Size([2, 1, 2, 2])


In [26]:
# torch.permute()
# Returns a view of the original input with its dimensions permuted (rearranged) to dims.
# viewを返す
x_original = torch.rand(size=(224, 224, 3))
x_permeted = torch.permute(x_original, (2, 0, 1))
print(x_permeted.shape)
print(x_original.shape)

# 同じメモリアドレスだから
# x_original[0, 0 ,0] = 111111
x_permeted[0, 0 ,0] = 2222

print(x_original[0, 0, 0], x_permeted[0, 0, 0])

torch.Size([3, 224, 224])
torch.Size([224, 224, 3])
tensor(2222.) tensor(2222.)


## Indexing (selecting data from tensors)

In [27]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x, x.shape)

# Let's index on our new tensor
print(x[0])
print(x[0][0])
print(x[0][0][0])

# you can also use ":" to select all of a target dimension
print(x[:, 0, :])
print(x[:, :, 0])

# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
print(x[:, 0, 0])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor([[1, 2, 3]])
tensor([[1, 4, 7]])
tensor([1])


## pytorch tensors and numpy
NumPyは人気のあるPython数値計算ライブラリであるため、PyTorchにはそれをうまく操作する機能があります。

NumPy から PyTorch への (およびその逆) に使用する主な 2 つの方法は次のとおりです。

* Data in numpy, want in pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> numpy -> `torch.tensor.numpy()`

In [28]:
from numpy import dtype
import numpy


array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
print(array.dtype)
print(array, tensor, tensor.dtype)

# change the value of array, what will this do to `tensor`
array = array * 10
print(array, tensor)

# tensor to numpy array
tensor = torch.ones(8)
numpy_tensor = tensor.numpy()
print(tensor, numpy_tensor, numpy_tensor.dtype)

# change the tensor, what hanppens to `numpy_tensor`
tensor = tensor * 10
print(tensor, numpy_tensor)

float64
[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.]) torch.float32
[10. 20. 30. 40. 50. 60. 70.] tensor([1., 2., 3., 4., 5., 6., 7.])
tensor([1., 1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1. 1.] float32
tensor([10., 10., 10., 10., 10., 10., 10., 10.]) [1. 1. 1. 1. 1. 1. 1. 1.]


## Reproducbility (trying to take random out of random)
再現性(ランダムからランダムを取り除こうとする)

ランダム性は素晴らしく強力ですが、ランダム性を少し減らしたい場合があります。

なぜでしょうか。

そのため、反復可能な実験を行うことができます。

たとえば、X パフォーマンスを達成できるアルゴリズムを作成するとします。

そして、あなたの友人はそれを試してみて、あなたが狂っていないことを確認します。

どうしてそんなことができるのだろう?

そこで、再現性の出番です。

言い換えれば、私が私のコンピュータで得るのと同じコードを実行しているあなたのコンピュータで同じ(または非常によく似た)結果を得ることができますか?

PyTorch での再現性の簡単な例を見てみましょう。

まず、2つのランダムなテンソルを作成しますが、それらはランダムであるため、異なると予想されますよね?

In [29]:
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4391, 0.6196, 0.7505, 0.7156],
        [0.9042, 0.2950, 0.4127, 0.0252],
        [0.5446, 0.3252, 0.6805, 0.1873]])
tensor([[0.2874, 0.8757, 0.1099, 0.1557],
        [0.6750, 0.5061, 0.6277, 0.4129],
        [0.6435, 0.6629, 0.5479, 0.1246]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


ご想像のとおり、テンソルは異なる値で出力されます。

しかし、同じ値を持つ 2 つのランダムなテンソルを作成する場合はどうでしょうか。

同様に、テンソルにはまだランダムな値が含まれていますが、それらは同じフレーバーになります。

そこで登場するのがtorch.manual_seed(seed)で、seedはランダム性を風味づける整数(42などですが、何でもかまいません)です。

もう少し風味豊かなランダムテンソルを作成して試してみましょう。

In [30]:
# Let's make some random but reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## GPUでテンソルを実行する(および計算を高速化する)
### PyTorchをGPU上で動作させる

In [31]:
# set device type
# device = "cuda" if torch.cuda.is_available() else "cpu"

### PyTorch を Apple Silicon で動作させる

In [32]:
# set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(device)

mps


### GPU にテンソル (およびモデル) を配置する

In [33]:
# create tensor
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

# move tensor to gpu
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='mps:0')


### テンソルを CPU に戻す

In [34]:
# NumPy は GPU を活用しません
# tensor_on_gpu.numpy() # error

# 代わりに、テンソルをCPUに戻し、
# NumPyで使用できるようにするには、 Tensor.cpu() を使用できます。
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)

[1 2 3]
