## 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)
import torch

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch


# Create random tensor
print(torch.rand(7, 7))

tensor([[0.8361, 0.9677, 0.1266, 0.7195, 0.7701, 0.4214, 0.1937],
        [0.6184, 0.3137, 0.1800, 0.9223, 0.8708, 0.9212, 0.3993],
        [0.2256, 0.9883, 0.3109, 0.1917, 0.9555, 0.8927, 0.3504],
        [0.0010, 0.3602, 0.5876, 0.3625, 0.3617, 0.9102, 0.9835],
        [0.7308, 0.4948, 0.6029, 0.2456, 0.5867, 0.8665, 0.9169],
        [0.0418, 0.9619, 0.7744, 0.3635, 0.8199, 0.1416, 0.5564],
        [0.3643, 0.5780, 0.9598, 0.1911, 0.5547, 0.5755, 0.5066]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [11]:
# Create another random tensor
tensor_A = torch.rand(1, 7)
tensor_B = torch.rand(1, 7)
# Perform matrix multiplication 
torch.matmul(tensor_A, tensor_B.T)


tensor([[2.2267]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
TENSOR_SEED = 0
torch.manual_seed(TENSOR_SEED)

# Create two random tensors
tensor_random_A = torch.rand(7, 7)
tensor_random_B = torch.rand(1, 7)

# Matrix multiply tensors
# torch.dotは1 次元ベクトルのみがサポートされています
# numpy.dot()とtorch.matmul()は同じ
Z = torch.matmul(tensor_random_A, tensor_random_B.T)
print(Z, Z.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.mps.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
torch.mps.manual_seed(1234)

# Check for access to GPU
device = "mps" if torch.backends.mps.is_available() else "cpu"

# Create two random tensors on GPU
A = torch.rand(2, 3).to(device=device)
print(A, A.device)
torch.mps.manual_seed(1234)
B = torch.rand(2, 3).to(device=device)
print(B, B.device)

tensor([[0.0340, 0.9442, 0.8802],
        [0.0012, 0.5936, 0.4158]], device='mps:0') mps:0
tensor([[0.4177, 0.2711, 0.6923],
        [0.2038, 0.6833, 0.7529]], device='mps:0') mps:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(A, B.T)
print(tensor_C, tensor_C.shape)

tensor([[0.8795, 1.3148],
        [0.4493, 0.7189]], device='mps:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
print(tensor_C.max())
# Find min
print(tensor_C.min())


tensor(1.3148, device='mps:0')
tensor(0.4493, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
print(tensor_C.argmax())

# Find arg min
print(tensor_C.argmin())


tensor(1, device='mps:0')
tensor(2, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_E = tensor_D.squeeze()


# Print out tensors and their shapes
print(tensor_E, tensor_E.shape)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
